version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-20211025
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: "4442"
      SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
      SE_NODE_GRID_URL: http://localhost:4444
      NODE_MAX_INSTANCES: ${NODE_MAX_INSTANCES}
      NODE_MAX_SESSION: ${NODE_MAX_SESSION}
    ports:
      - "6900:5900"
    networks:
      - reactapp_network

  edge:
    image: selenium/node-edge:4.0.0-20211025
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: "4442"
      SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
      SE_NODE_GRID_URL: http://localhost:4444
      NODE_MAX_INSTANCES: ${NODE_MAX_INSTANCES}
      NODE_MAX_SESSION: ${NODE_MAX_SESSION}
    ports:
      - "6901:5900"
    networks:
      - reactapp_network

  firefox:
    image: selenium/node-firefox:4.0.0-20211025
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: "4442"
      SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
      SE_NODE_GRID_URL: http://localhost:4444
      NODE_MAX_INSTANCES: ${NODE_MAX_INSTANCES}
      NODE_MAX_SESSION: ${NODE_MAX_SESSION}
    ports:
      - "6902:5900"
    networks:
      - reactapp_network

  selenium-hub:
    image: selenium/hub:4.0.0-20211025
    container_name: selenium-hub
    environment:
      GRID_MAX_SESSION: ${GRID_MAX_SESSION}
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - reactapp_network

networks:
  reactapp_network:
    external: true
